name: Checkout, pipenv install and run
description: Checkout, pipenv install and run

inputs:
  fetch-depth:
    required: false
    description: The number of commits to fetch
    default: "0"

  submodules:
    required: false
    description: Whether to fetch submodules
    default: ""

  python-version:
    required: false
    description: Version of Python to install
    default: "3.7"

  pipenv-install:
    required: false
    description: The options to pass to pipenv install
    default: "--dev --deploy"

  pipenv-run:
    required: false
    description: If given, run pipenv run with these arguments
    default: ""

  allow-editable-installs:
    required: false
    description: If false then change Pipfile references to editable to false
    default: "true"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        submodules: ${{ inputs.submodules }}

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - if: ${{ inputs.allow-editable-installs != 'true' }}
      shell: bash
      run: sed -i 's/editable *= *true/editable = false/' Pipfile

    - shell: bash
      run: pip install pipenv

    - shell: bash
      run: pipenv install --python ${{ inputs.python-version }} ${{ inputs.pipenv-install }}

    - shell: bash
      run: pipenv graph

    - if: inputs.pipenv-run
      shell: bash
      run: pipenv run ${{ inputs.pipenv-run }}
